// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCDX2pLOU4iLUr9FygLJRANAiroQBLVI',
    appId: '1:597391607537:web:65b641dc35902623c4cb50',
    messagingSenderId: '597391607537',
    projectId: 'hospital-system-6fa02',
    authDomain: 'hospital-system-6fa02.firebaseapp.com',
    storageBucket: 'hospital-system-6fa02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy39RoTtvUkGZiTpEmnEGra6kacwYTfdA',
    appId: '1:597391607537:android:d365a0031de641afc4cb50',
    messagingSenderId: '597391607537',
    projectId: 'hospital-system-6fa02',
    storageBucket: 'hospital-system-6fa02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpe1Mjl4OgtWb1Zp2Hv87qjBbEwOqsiT0',
    appId: '1:597391607537:ios:578f14f5ff106c80c4cb50',
    messagingSenderId: '597391607537',
    projectId: 'hospital-system-6fa02',
    storageBucket: 'hospital-system-6fa02.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpe1Mjl4OgtWb1Zp2Hv87qjBbEwOqsiT0',
    appId: '1:597391607537:ios:22c83c15040d511ec4cb50',
    messagingSenderId: '597391607537',
    projectId: 'hospital-system-6fa02',
    storageBucket: 'hospital-system-6fa02.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler.RunnerTests',
  );
}
