// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdg8Z_qJKO4JBmkCThDIfw-Mu7ddfj49E',
    appId: '1:806233887962:web:68af51cde31a4e548401e3',
    messagingSenderId: '806233887962',
    projectId: 'uzaydan-misafirler',
    authDomain: 'uzaydan-misafirler.firebaseapp.com',
    storageBucket: 'uzaydan-misafirler.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rtI3qcdFFpIpF02ROdH8MvWrkV3iMgU',
    appId: '1:806233887962:android:8d0edfc04a243b868401e3',
    messagingSenderId: '806233887962',
    projectId: 'uzaydan-misafirler',
    storageBucket: 'uzaydan-misafirler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UIjJQOzKrze_QBT5GG8nmFuRRXK9be8',
    appId: '1:806233887962:ios:bfd1f2dd68ecae778401e3',
    messagingSenderId: '806233887962',
    projectId: 'uzaydan-misafirler',
    storageBucket: 'uzaydan-misafirler.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UIjJQOzKrze_QBT5GG8nmFuRRXK9be8',
    appId: '1:806233887962:ios:ee84998654c5dffe8401e3',
    messagingSenderId: '806233887962',
    projectId: 'uzaydan-misafirler',
    storageBucket: 'uzaydan-misafirler.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler.RunnerTests',
  );
}
